In [9]:
import numpy as np
#将X，y赋值为np数组
X = np.array([[0, 1, 0, 1], 
              [1, 1, 1, 0], 
              [0, 1, 1, 0], 
              [0, 0, 0, 1], 
              [0, 1, 1, 0], 
              [0, 1, 0, 1], 
              [1, 0, 0, 1]])
y = np.array( [0, 1, 1, 0, 1, 0, 0])
#对不同分类计算每个特征为1的数量
counts = {}
for label in np.unique(y):
    counts[label] = X[y == label].sum(axis=0)
print("feature counts:\n{}".format(counts))

feature counts:
{0: array([1, 2, 0, 4]), 1: array([1, 3, 3, 0])}


In [10]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X, y)
#要进行预测的这一天，没有刮北风，也不闷热
#但是多云，天气预报没有说有雨
Next_Day = [[0, 0, 1, 0]]
pre = clf.predict(Next_Day)
if pre == [1]:
    print("要下雨啦，快收衣服啊！")
else:
    print("放心，又是一个艳阳天")
    
pre    

要下雨啦，快收衣服啊！


array([1])

In [11]:
Another_day = [[1, 1, 0, 1]]
pre2 = clf.predict(Another_day)
if pre2 == [1]:
    print("要下雨啦，快收衣服啊！")
else:
    print("放心，又是一个艳阳天")

放心，又是一个艳阳天


In [12]:
clf.predict_proba(Next_Day)

array([[0.13848881, 0.86151119]])

In [13]:
clf.predict_proba(Another_day)

array([[0.92340878, 0.07659122]])

In [ ]:
练习
1.一家公司想要根据客户在其网站上的统计信息和浏览行为来预测客户是否可能购买产品。
该公司已经收集了一个包含10个客户的小数据集，每个客户有5个特征和一个二进制标签，表示他们是否购买了产品。
使用伯努利朴素贝叶斯算法对客户进行分类，并根据其统计信息和浏览行为预测新客户是否可能购买。
# define input data
X = np.array([[1, 1, 1, 0, 0],
              [0, 1, 1, 0, 0],
              [1, 0, 1, 1, 0],
              [0, 0, 0, 1, 1],
              [0, 0, 0, 1, 1],
              [0, 1, 0, 1, 1],
              [1, 0, 0, 0, 0],
              [1, 1, 1, 1, 0],
              [0, 1, 0, 0, 1],
              [1, 1, 1, 1, 1]])

# define labels
y = np.array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1])

# new customer
new_customer = [[1, 0, 0, 1, 0]]

In [6]:
import numpy as np
X = np.array([[1, 1, 1, 0, 0],
              [0, 1, 1, 0, 0],
              [1, 0, 1, 1, 0],
              [0, 0, 0, 1, 1],
              [0, 0, 0, 1, 1],
              [0, 1, 0, 1, 1],
              [1, 0, 0, 0, 0],
              [1, 1, 1, 1, 0],
              [0, 1, 0, 0, 1],
              [1, 1, 1, 1, 1]])

# define labels
y = np.array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1])

# new customer
new_customer = [[1, 0, 0, 1, 0]]
#对不同分类计算每个特征为1的数量
counts = {}
for label in np.unique(y):
    counts[label] = X[y == label].sum(axis=0)
print("feature counts:\n{}".format(counts))

feature counts:
{0: array([2, 4, 2, 1, 2]), 1: array([3, 2, 3, 5, 3])}


In [7]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X, y)
pre = clf.predict(new_customer)
if pre == [1]:
    print("会买")
else:
    print("不会买")

会买
