In [12]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
en = ['The quick brown fox jumps over a lazy dog']
vect.fit(en)
print('单词数：{}'.format(len(vect.vocabulary_)))
print('分词：{}'.format(vect.vocabulary_))#给每个字确定一个编号

单词数：8
分词：{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumps': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [13]:
vect

CountVectorizer()

In [14]:
cn = ['那只敏捷的棕色狐狸跳过了一只懒惰的狗']
vect.fit(cn)
print('单词数：{}'.format(len(vect.vocabulary_)))
print('分词：{}'.format(vect.vocabulary_))

单词数：1
分词：{'那只敏捷的棕色狐狸跳过了一只懒惰的狗': 0}


In [15]:
import jieba
cn = jieba.cut('那只敏捷的棕色狐狸跳过了一只懒惰的狗')
cn = [' '.join(cn)]
print(cn)

['那 只 敏捷 的 棕色 狐狸 跳过 了 一只 懒惰 的 狗']


In [16]:
vect.fit(cn)
print('单词数：{}'.format(len(vect.vocabulary_)))
print('分词：{}'.format(vect.vocabulary_))

单词数：6
分词：{'敏捷': 2, '棕色': 3, '狐狸': 4, '跳过': 5, '一只': 0, '懒惰': 1}


In [17]:
bag_of_words = vect.transform(cn)
print('转化为词袋的特征：\n{}'.format(repr(bag_of_words)))
print(bag_of_words)
print('词袋的密度表达：\n{}'.format(bag_of_words.toarray()))

转化为词袋的特征：
<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>
  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
词袋的密度表达：
[[1 1 1 1 1 1]]


In [18]:
cn_1 = jieba.cut('懒惰的狐狸不如敏捷的狐狸敏捷,敏捷的狐狸不如懒惰的狐狸懒惰')
cn2 = [' '.join(cn_1)]
print(cn2)
print('分词：{}'.format(vect.vocabulary_))

['懒惰 的 狐狸 不如 敏捷 的 狐狸 敏捷 , 敏捷 的 狐狸 不如 懒惰 的 狐狸 懒惰']
分词：{'敏捷': 2, '棕色': 3, '狐狸': 4, '跳过': 5, '一只': 0, '懒惰': 1}


In [19]:
new_bag = vect.transform(cn2)
print('转化为词袋的特征：\n{}'.format(repr(new_bag)))
print('词袋的密度表达：\n{}'.format(new_bag.toarray()))
print(new_bag)

转化为词袋的特征：
<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>
词袋的密度表达：
[[0 3 3 0 4 0]]
  (0, 1)	3
  (0, 2)	3
  (0, 4)	4


# 假设你有一段包含多个中文句子的文本数据，你想分词、使用CountVectorizer进行文本特征提取和构建词袋模型并输出文本中的单词数目和分词结果。

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
import jieba

In [31]:
# 定义文本数据
text = [
    "我喜欢吃披萨",
    "披萨是我最喜欢的食物",
    "我喜欢和朋友一起吃披萨"
]

# 中文分词
text_segmented = [' '.join(jieba.cut(sentence)) for sentence in text]

# 创建CountVectorizer对象
vect = CountVectorizer()

# 拟合数据，提取文本特征
vect.fit(text_segmented)

# 输出单词数目和分词结果
print("单词数：{}".format(len(vect.vocabulary_)))
print("分词：{}".format(vect.vocabulary_))

单词数：5
分词：{'喜欢': 1, '披萨': 2, '食物': 4, '朋友': 3, '一起': 0}


In [33]:
# 定义文本数据
text = [
    "我喜欢吃披萨",
    "披萨是我最喜欢的食物",
    "我喜欢和朋友一起吃披萨",
    "我也喜欢面条"
]

# 中文分词
text_segmented = [' '.join(jieba.cut(sentence)) for sentence in text]

# 创建CountVectorizer对象拟合数据，提取文本特征
vect = CountVectorizer().fit(text_segmented)

# 输出单词数目和分词结果
print("单词数：{}".format(len(vect.vocabulary_)))
print("分词：{}".format(vect.vocabulary_))

['我 喜欢 吃 披萨', '披萨 是 我 最 喜欢 的 食物', '我 喜欢 和 朋友 一起 吃 披萨', '我 也 喜欢 面条']
单词数：6
分词：{'喜欢': 1, '披萨': 2, '食物': 5, '朋友': 3, '一起': 0, '面条': 4}


任务：计算三句话中短语（长度>=2）的数量以及给这些短语编号
代码没有问题，将list中每个句子看作一个文本，在句子数量很多且并不重视句子之间关系时，可将句子合并为一个文本
结果变化如上图

In [47]:
# 定义文本数据
text = [
    "我喜欢吃披萨",
    "披萨是我最喜欢的食物",
    "我喜欢和朋友一起吃披萨"
]
# 中文分词
sen = ''
for s in text:
    sen=sen+' '+s
sen_s = [' '.join(jieba.cut(sen))]

# 创建CountVectorizer对象
vect = CountVectorizer()

# 拟合数据，提取文本特征
vect.fit(sen_s)

# 输出单词数目和分词结果
print(sen_s)
print("单词数：{}\n".format(len(vect.vocabulary_)))
print("分词：{}\n".format(vect.vocabulary_))
bag = vect.transform(sen_s)
print('词袋的密度表达：\n{}\n'.format(bag.toarray()))
print(bag)

['  我 喜欢 吃 披萨   披萨 是 我 最 喜欢 的 食物   我 喜欢 和 朋友 一起 吃 披萨']
单词数：5

分词：{'喜欢': 1, '披萨': 2, '食物': 4, '朋友': 3, '一起': 0}

词袋的密度表达：
[[1 3 3 1 1]]

  (0, 0)	1
  (0, 1)	3
  (0, 2)	3
  (0, 3)	1
  (0, 4)	1
